gexijin/idepGolem

R/mod_01_load_data.R
dev/run_dev.R

-selectizeInput had allowed for the returning of an empty string which would cause the app to crash
-FIX: changed to selectInput with selectize = TRUE as a parameter
-also changed updateSelectizeInput to updateSelectInput
https://www.rdocumentation.org/packages/shiny/versions/0.9.1/topics/selectInput
close #41

fix selectizeInput

---

R/mod_01_load_data.R

This is the exact code and size that can be found in the original iDEP

66 file size

---

R/mod_01_load_data.R

- updateSelectInput -> updateSelectizeInput
- this fixes the error that we were getting while still preventing the app from crashing
closes #72

update server side selectinput

---

DESCRIPTION
R/mod_03_clustering.R
dev/02_dev.R

**What:** 
Added elbow plot as pop-up 
Removed elbow plot as mini-tab
Added shinyBS as included library 
closes #65

65 kmeans elbow plot

---

R/mod_03_clustering.R

part of clustering tab refactoring 
closes #68

68 remove heatmap table 

---

R/mod_03_clustering.R

Move enrichment analysis from the mini-tab below the heatmap information for clarity. 
closes #69

69 move enrichment

---

DESCRIPTION
R/fct_05_deg.R
R/mod_05_deg.R
man/MDS_plot.Rd
man/PCA_plot.Rd
man/plot_ma.Rd
man/plot_volcano.Rd
man/t_SNE_plot.Rd

83 add color option

---

R/fct_03_clustering.R

- Turned sample tree direction from vertical to horizontal
-Altered  the margins of the plot, so that most sample titles should be fully readable.
closes #88

Updated draw_Sample_tree function

---

R/mod_03_clustering.R
man/MDS_plot.Rd
man/PCA_plot.Rd
man/t_SNE_plot.Rd

- Removed correlation plot and associated code from mod_03.
- Did NOT remove correlation plot function
- closes #79 
- closes #60 
- closes #59

Removed correlation plot

---

R/fct_03_clustering.R
R/mod_03_clustering.R
vignettes/idep_Workflow.Rmd

- I had previously made a mistake that caused the function to return 5 less genes than what was specified.
- Since we no longer want to option for "minimim gene", I removed all that code in the functionl; now the function returns the 1:n genes with the most variability.
- I removed some of the now redudant if statements
- I upped the minimum genes in the selectInput function in the module from 5 to 10 to match internal logic
- I added an if statment that changes and input into the function less than 10 to 10
- closes #90

Updated process_heatmap_data

---

R/app_server.R
R/fct_05_deg.R
R/mod_05_deg.R
man/enrichment_plot.Rd

Fix to code so now the plot displays
closes #54 
closes #49 
closes #45

54 enrich tree margins

---

R/fct_03_clustering.R

closes #58 
- Added description for error instead of just a random message

58 error elbow plot

---

R/fct_06_pathway.R
R/fct_database.R
man/kegg_pathway_id.Rd

Fixed typo and parameter error. KEGG pathway plots now generate correctly. 
closes #95

95 error with kegg pathway

---

R/fct_06_pathway.R
R/mod_06_pathway.R
man/kegg_pathway.Rd
man/kegg_pathway_id.Rd

Added conditional statement, so only the kegg map colors show up. 
Users now have the option too have the map be red/green or blue/orange (color-blind friendly) 
closes #61 
closes #100

61 kegg colors

---

R/mod_03_clustering.R

Add conditional panels to control what options are shown in the side panel to reflect what can actually change the graph in the subtabs. 
closes #104

104 sample tree

---

R/mod_download_images.R

1. Add more comments
2. Add checks on figure size inputs using reactive functions
3. Closes popup after any download
4. Minor style changes
5. Changed min and max figure sizes

Refine download module

---

R/mod_05_deg.R
vignettes/idep_Workflow.Rmd

Removed gene column(s) from enrichment analysis data table 
Added download option for data 
closes #114

114 gene column deg2

---

R/mod_05_deg.R
R/mod_download_images.R

1. Add parameters in the server function to specify width and height
2. Add parameter in the ui function to customize label.
3. disable close popup by default

Further enhancement of the download image module

---

R/fct_database.R
R/mod_10_doc.R

This solves issue #122 
https://github.com/espors/idepGolem/issues/122
closes #122

Add citation info for pathview, KEGG and others.

---

R/fct_02_pre_process.R
R/fct_04_pca.R
R/mod_02_pre_process.R
R/mod_04_pca.R

Also added aspect ratio display to pca plot.
.

Miscellaneous bugs fixes for LFC and p-val data

---

R/mod_05_deg.R

- removed old code that was no longer needed
- added ottoPlots version
- download venn plots

Updated dl venn plot

---

R/fct_04_pca.R
vignettes/idep_Workflow.Rmd

The idep_Wokrflow.RMD document can now be knitted. It loads data files, and generates a majority of all the plots by calling the idepGolem functions. Some of the later tab plots were commented out because they would not run. This idep_workflow.rmd document is useful for debugging and testing. You can change the files and the parameters then knit the document to check if the functions run correctly.

Vignette ben

---

R/app_server.R
R/fct_database.R
R/mod_01_load_data.R

Improve the gene ID conversion

---

R/fct_database.R

1. Number of sample gene ids variable
2. Number of sample gene ids equals query when  query is small.
3. Simplified the logic for matched species

simplified   convert_id function

---

R/fct_04_pca.R
R/mod_03_clustering.R
R/mod_04_pca.R
R/utils_analysis_random.R
vignettes/Reports/clustering_workflow.Rmd
vignettes/idep_Workflow.Rmd

Added Clustering Tab Markdown Report. The report is functional but I intent to add more to it.

43 preprocess report

---

R/fct_02_pre_process.R
R/fct_database.R
R/mod_01_load_data.R
R/mod_02_pre_process.R
R/utils_analysis_random.R

1. UI adjustment for pre-process
2. Plot a random gene in Preprocess--> Gene Plot 
3. Fixed gene ID issue

Deployment

---

R/mod_02_pre_process.R
R/mod_03_clustering.R

Simplified UI.
Improved speed by hiding enrichment analysis

Improve UI for Clustering

---

R/fct_01_load_data.R
R/fct_database.R
R/mod_01_load_data.R
man/input_data.Rd

Note that the corresponding files needs to be in the go_data subfolder of the database:
"GSE37704_Hoxa1_normalized.csv",   #2 Hoxa1 vs control
"GSE71176_p53_LFC_FDR.csv"             #3 FC & FDR

Add demo files for all data formats

---

R/fct_01_load_data.R
R/fct_database.R
R/mod_01_load_data.R
man/counts_bias_message.Rd
man/input_data.Rd

Add a demo_file_info.csv file which lists the many demo files and the corresponding design files
UI changes

multiple demo and design files

---

R/fct_05_deg.R
man/transform_comparisons.Rd

Initially only the first factor is used.

Fix bug when there are two or more block factors in limma

---

R/fct_01_load_data.R
R/fct_database.R
R/mod_01_load_data.R
R/mod_02_pre_process.R
man/convert_id.Rd

Bring recent changes from iDEP & ShinyGO
Fix error when ID is not recognized.

debug convert_id function

---

R/fct_05_deg.R
R/mod_05_deg.R
man/deg_deseq2.Rd
man/limma_value.Rd

Testing null hypothesis that the fold-change is bigger than a value.
https://github.com/espors/idepGolem/issues/197

Add threshold-based Wald test to DESeq2

---

R/app_server.R
R/fct_07_genome.R
R/fct_database.R
R/mod_07_genome.R

1. Fix error with PREDA. Some functional calls cannot be resolved unless PREDA is loaded via library(PREDA)
2. Turn off warning messages with options(warn=-1)
3. Rearrange Genome tab

Fix error with PREDA

---

R/app_server.R

error writing to Rplots.pdf
pdf(file = NULL)

Try to solve the visNetwork error

---

R/mod_06_pathway.R

Fixed this issue https://github.com/espors/idepGolem/issues/217

UI for Pathway analysis; KEGG pathway for all pathways

---

R/mod_06_pathway.R

https://github.com/espors/idepGolem/issues/228

Fixed issue 228 by removing spinners and use progress bar

---

R/mod_01_load_data.R

Tests if the minimum value of input data is less than zero when the Read Counts data type is selected. 
If there is a negative value, the user gets a pop-up window warning them if something is wrong, and when they acknowledge the message the app resets. The app must reset because otherwise, the data preparation set will crash the application when there are negative values. 
Closes #229 
Closes #233

229 demo data

---

R/mod_02_pre_process.R

Added requirement statements to gene plot to prevent the app from trying to render the plot without all of the inputs
Successfully removed the error
closes #165

Added requirement statements to gene plot

---

R/fct_03_clustering.R
R/fct_analysis_random.R
R/mod_03_clustering.R
R/mod_11_enrichment.R

Enrichment results2

---

R/mod_03_clustering.R

Added an additional requirement to the if statement to prevent the cluster_heat_click_info() function from executing before all the inputs were available
closes #56

Added an additional requirement

---

R/fct_08_bicluster.R
R/fct_09_network.R
R/mod_03_clustering.R
R/mod_05_deg.R
R/mod_08_bicluster.R
R/mod_09_network.R
R/mod_11_enrichment.R
man/get_biclust_table_data.Rd
man/get_network_plot.Rd

Use modules to calculate enrichment in 4 tabs

Module enhancement

---

R/mod_11_enrichment.R

Add barplot to enrichment module

---

R/fct_03_clustering.R
R/mod_03_clustering.R
R/utils_analysis_random.R
man/heatmap_main.Rd
pathway_table_bg.csv

1. Switched the No_sample_clustering to the oposite
2. Add a conditional button for additional settings.

Reorganize clustering tab

---

R/fct_03_clustering.R
R/fct_12_heatmap.R
R/mod_02_pre_process.R
R/mod_03_clustering.R
man/heatmap_main.Rd

Not fully working, gene ids does not populate from list

Heatmap improvement

---

R/mod_05_deg.R

Added submit button into UI to only show when the comparisons have been generated
closes #273

Added submit button into UI

---

R/fct_02_pre_process.R
R/fct_database.R

Fixed data preparations steps in related functions to work for dataset with a lot of samples 
closes #270

Fix issues related to large datasets [Preprocess]

---

R/fct_05_deg.R
R/fct_07_genome.R
R/mod_07_genome.R

Fix error with genome plot

---

R/mod_01_load_data.R
R/mod_02_pre_process.R
R/mod_03_clustering.R
R/mod_04_pca.R
R/mod_05_deg.R
R/mod_06_pathway.R
R/mod_07_genome.R
R/mod_08_bicluster.R
R/mod_09_network.R
R/mod_10_doc.R

Also fixed a bug in the show message when DEG is not run!!

Show message when data is not loaded

---

R/mod_01_load_data.R

Added require statement to demo_data_file so that the function would not run before the input was ready
closes #285

Added require statement to demo_data_file

---

R/mod_01_load_data.R

Add tippy to buttons in load data tab 
in support of #113

Add tippy to buttons in load data tab

---

R/fct_database.R
R/mod_03_clustering.R

Added tippy notes to clustering tab 
In support of #113

Tippy clustering

---

R/mod_04_pca.R

Add tippy descriptions to PCA tab 
In support of #113

Add tippy to PCA tab

---

R/mod_05_deg.R
R/mod_06_pathway.R

Add tippy notes to deg and pathway tabs 
In support of #113

Add tippy notes to deg and pathway tabs

---

R/mod_11_enrichment.R

Add tippy descriptions to enrichment module 
Closes #113

Add tippy information to enrichment analysis

---

R/fct_01_load_data.R
man/prep_venn.Rd

Removed excess characters from row names in the experiment file to fix certain analyses. 
Closes #274 
Closes #275 
Closes #298

Lg. dataset issues 

---

R/mod_01_load_data.R

Add a pop-up modal for citation to improve visibility of the need to cite the application. 
Closes #337

Add pop-up modal for citation

---

R/fct_05_deg.R
R/mod_05_deg.R

Increased font size
Remove labels
Add plot information

Updates to upset plot

---

R/fct_05_deg.R

Removed genes not in any intersection

---

R/mod_01_load_data.R

Update from bsmodal to shiny modal

---

R/mod_01_load_data.R

added if else statement to detect if the input values had not been populated yet -- adds default values if not. Works, may not be the most efficient.

patch for when pop-up modal is not clicked

---

R/fct_02_pre_process.R
R/mod_02_pre_process.R
man/total_counts_ggplot.Rd

add processed counts barplot to preprocess tab
closes #304

transformed counts barplot

---

R/app_ui.R
R/mod_01_load_data.R
R/mod_03_clustering.R

1. Plot options on the Load Data tab
2. Heatmap options on the Clustering tab

Fixed pop-up windows for options using Shinyjs

---

R/app_ui.R
R/mod_01_load_data.R
R/mod_02_pre_process.R

The gene plot is fixed just by deleting this line. Don't ask me why.   req(tab() == "Pre-Process")

Fix gene plot

---

R/app_ui.R

Add correct id to the navbar
Closes #400

Fix tab reactivity

---

R/fct_01_load_data.R
man/convert_data.Rd
man/gene_info.Rd
man/get_all_gene_names.Rd
man/input_data.Rd

Update load data documentation

Update load data documentation

---

R/fct_05_deg.R
R/mod_05_deg.R
R/mod_06_pathway.R
vignettes/Reports/pathway_workflow.Rmd
vignettes/idep_Workflow.Rmd

added deg info to processing summary. This can be accessed/ located at deg$limma$description or deg$limma[["description"]] works better.

DEG summary

---

R/fct_02_pre_process.R
R/fct_05_deg.R

Added a centered dot plot (like jitter) to the gene bar plot in the preprocessing tab

Add dot plot to gene plot

---

R/fct_01_load_data.R

https://github.com/gexijin/idepGolem/issues/444

Fix error when design file has rows with one unique level

---

R/app_server.R
R/fct_01_load_data.R
R/fct_02_pre_process.R

If there is a missing value, the entire gene is removed. This is fixed.

Fix missing value problem

---

R/mod_01_load_data.R

made the additional options appear to user without having to click a button, updated some labels on load tab, fixed a typo

issue #548

---

R/fct_08_bicluster.R
R/fct_09_network.R
R/mod_09_network.R

This should fix #526 please check out this branch and test it. If changes are needed please comment before merging.

526 download all modules

---

R/fct_05_deg.R
R/mod_05_deg.R

added a download option for the DEG1 tab's results bar plot, also fixed a typo in the bar plot's axis label

deg1 results bar plot, add download button

---

R/fct_01_load_data.R
R/mod_01_load_data.R
R/mod_02_pre_process.R

now able to read "1,120" strings as numbers. I did this for csv and tab format to keep the workflow the same.
This fixes #554 issue, BUT I have a questions
If a cell has NA how do we want to handle it? 
suggestion:
We remove the Gene(row) and inform the user that a Cell had NA value and that Row was removed

allow string numbers to be read in as 

---

R/fct_01_load_data.R
R/mod_01_load_data.R
R/mod_02_pre_process.R

Reverts gexijin/idepGolem#569 need to do more testing

Revert "allow string numbers to be read in as "

---

R/app_server.R
R/fct_01_load_data.R
R/mod_01_load_data.R
R/mod_02_pre_process.R

If a row has NA, we do not remove them. There are methods down in the process to handle them.

Revert "Enhanced Number Parsing & Handling of NA Values"

---

R/fct_01_load_data.R

This fixes https://github.com/gexijin/idepGolem/issues/554 issue 
While testing, I ran into the following error:
if a row has all NA downstream fails. 
For now, rows with all NA get turned into rows with all 0.
Have code to remove those rows commented out we can do either chose.
error files 
[GSE37704_sailfish_genecounts_with_NA.csv](https://github.com/gexijin/idepGolem/files/12887976/GSE37704_sailfish_genecounts_with_NA.csv)
[JAN7448_processed_exon_featureCounts_raw_KCNJ16.1.txt](https://github.com/gexijin/idepGolem/files/12887977/JAN7448_processed_exon_featureCounts_raw_KCNJ16.1.txt)

Enhanced number parsing

---

R/mod_01_load_data.R

Fix https://github.com/gexijin/idepGolem/issues/533

Display data as loaded instead of converted.

---

R/fct_01_load_data.R
R/mod_01_load_data.R

Fix a bug in reading expression file.
Enable reading design file as Excel

Read file in Excel for design file

---

R/mod_05_deg.R

I think this is what #578 is asking for. Please le me know if other information is wanted for this issue.
Here is an example of the file 
[deg_sig_genes_DESeq2.csv](https://github.com/gexijin/idepGolem/files/12969858/deg_sig_genes_DESeq2.csv)

draft for allowing user to download data

---

R/fct_02_pre_process.R
R/mod_02_pre_process.R
dev/run_dev.R
inst/app/www/RMD/pre_process_workflow.Rmd

Added QR plot. Gene plot not included yet. Still looking for bug.

Plots on pre process markdown

---

R/fct_01_load_data.R
R/mod_01_load_data.R
man/sig_genes_plot.Rd

For Issue #587 I added text inside the upload data box to tell the user they can drag and drop files from their computer.
For Issue #589 I corrected the experimental input data variable name.

Fix for Issue #587 and #589

---

R/mod_04_pca.R
R/mod_06_pathway.R

https://github.com/gexijin/idepGolem/issues/593

Fix issue with 3D PCA plot

---

R/app_server.R
R/fct_02_pre_process.R
R/fct_04_pca.R
R/fct_05_deg.R
R/mod_01_load_data.R
R/mod_02_pre_process.R
R/mod_04_pca.R
R/mod_05_deg.R
man/MDS_plot.Rd
man/PCA_plot.Rd
man/PCA_plot_3d.Rd
man/eda_boxplot.Rd
man/eda_density.Rd
man/gene_counts_ggplot.Rd
man/individual_plots.Rd
man/plot_venn.Rd
man/rRNA_counts_ggplot.Rd
man/t_SNE_plot.Rd
man/total_counts_ggplot.Rd

Added a "plot color select" option in the load data tab (global settings) with color blind friendly color options. Changes 12 ggplot graphs' colors to fit the chosen scheme.

issue #594

---

R/fct_05_deg.R
R/fct_11_enrichment.R
R/fct_12_heatmap.R
R/mod_05_deg.R
man/enrichment_tree_plot.Rd
man/plot_volcano.Rd

This runs fine with the demo data on my machine. I do not have much other data to test it further with, but I would be happy to if someone send me some. I was not sure how we wanted to format a long matrix filter such as lines 919-920 of mod_05_deg.R as it is longer than the 80 character margin without any clear breaks. I do not know if this is an issue.

DEG2 tab additions

---

DESCRIPTION
R/fct_04_pca.R

Names of each point on the 3D PCA plot now match the names from the data

3D PCA Names Fixed

---

R/mod_01_load_data.R

"No data type selected" --> "..."
Deemphasize "Custom" button as it is not relevant to most people. 
Breviate message.

Minor UI adjust to load data.

---

R/mod_01_load_data.R

* Error was created on first fix for User Manual Selection
* Now data type selection should remain consistent instead of being stuck on Counts type

Data Selection Fix

---

R/fct_09_network.R
R/mod_09_network.R
man/prepare_module_csv_filter.Rd

* Fixed error in individual network module downloads where all modules were downloaded regardless of module selection
* This was referenced in Issue #526

Network module download fix

---

R/fct_05_deg.R
R/mod_06_pathway.R

* Added baseMean column to DESeq2 downloadable file
* BaseMean information is not generated for limma DEG methods, so the new column is only available for DESeq2
* Reorganized deg_information function
Extra: Added download icon to "Gene List" button on Pathway Tab

DEG1 BaseMean Column

---

R/fct_06_pathway.R
R/mod_06_pathway.R
man/pathway_select_data.Rd

* Added "Regulation" column in Gene List data download in the Pathway/Significant Pathways tab
* Displays regulation of a given gene from the selected pathway ("Up", "Down", or "None")
* Improved dynamic file names to work for non-standard database options (those outside of KEGG, GOBP, etc.)

Gene List Data Addition

---

R/mod_02_pre_process.R

* Added a table to the Barplot section of the Pre-Process tab to show gene counts before and after filtering as well as the counts lost via filtering

Read Counts Table

---

R/fct_03_clustering.R
R/mod_03_clustering.R

* Fixed selectInput for heatmap group colors not toggling with customization options
* Fixed error with legend generation on heatmap

Fixed Conditional Errors

---

R/mod_05_deg.R

* Added a new warning type to DEG1 tab
* If a user does not select comparisons for DEG1 analysis, a modal will appear with an error message, informing users to resubmit after selecting

DEG1 Comparison Warning

---

R/mod_01_load_data.R

* Moved tutorial video/demo data text to main panel
* Expanded video/demo instructions into "First Steps" instructions
* Tells user to select species and data type prior to loading a demo

Demo Data Prompt Change

---

R/mod_02_pre_process.R

Issue #671 :
* Updated message to be more clear to user

Updated Message

---

R/mod_03_clustering.R
R/mod_12_heatmap.R

* Added new reactive values to ensure that the enrichment module of the Clustering tab refreshes correctly
* Refreshes on sub-heatmap selection for hierarchical clustering
* Refreshes every time new clusters are generated for k-means
* No longer incorrectly refreshes on sub-heatmap generation for k-means

K Means Enrichment Refresh Fix

---

R/mod_04_pca.R
R/mod_05_deg.R
R/mod_07_genome.R

* Removed submit buttons from the PCA, DEG2, and Genome tabs by request
* This will help avoid some confusion for users on tabs without many parameters

Remove Submit Buttons

---

R/fct_database.R

* Changed "Subtype.Database.name" column in pathway_source_info() SQL query to "Database" to match updated name in **data113**

Fix Enrichment Details

---

R/mod_05_deg.R

* Fixed error where DEG1 analysis wouldn't run for "Fold change and adjusted p-values" data type
* Error message no longer occurs every time DEG1 is ran with 3rd data type

Third Data Type Error

---

R/mod_01_load_data.R

* Allowed for unsupported species to be entered using the "Custom/New" button on the "Load Data" tab
* Similar to entering a custom species with a .gmt file, but users can now select "Continue" within the modal if they do not have a .gmt file
* Removed unnecessary encoding of "Human" and "None" in species selection options
* Default selection is now strictly "None," not encoded as 999

New Species Selection Fix
