gexijin/idepGolem

R/mod_03_clustering.R, man/MDS_plot.Rd, man/PCA_plot.Rd, man/t_SNE_plot.Rd
Removed options for sampling centering/normalization 
The default is not FALSE for sample centering and sample normalization 
Let the underlying code, so some one using the code as a package could change the parameters 
Left the option for gene centering/normalization 
closes #67
=> 67 remove sample options

R/mod_03_clustering.R, man/kegg_pathway_id.Rd
Remove gene column from enrichment data table. It is still included in the downloadable version. 
closes #101
=> 101 remove gene column

R/mod_03_clustering.R
Added showTab and hideTab functions in the server to control when the sample tree tab in shown. Because the sample tree is only generated for hierarchical clustering, the tab is not shown when k-means clustering is selected. Updated the reference to the tab to 'sample_tab'
closes #111
=> Added conditionals to control when the sample tree was shown

R/fct_05_deg.R, R/mod_05_deg.R
- there was an error in the limma_value() function where the wrong datafile name was left in the code from coping over from the old idep
- added a clause to the list_model_comparisons html output so that the comparisons are not displayed when the data type of LFC
closes #188
=> Updated DEG1 for LFC Data

R/mod_01_load_data.R, R/mod_02_pre_process.R
Add tippy to pre-processing tab and switched transformation type from radioButtons to selectInput to support minimal design.
In support of #113
=> Add tippy to pre-processing tab 

R/mod_03_clustering.R, R/mod_12_heatmap.R
The height of the sub heatmap is adjusted dynamically depending on the number of genes selected. This way gene symbols are always readable.
=> Dynamically scale sub heatmap

R/fct_04_pca.R, R/mod_04_pca.R
This fixes the #493, 
Though I notice this error on PCA with both my branch and main 
output$pca_plot_obj <- renderPlot({
req(pca_plot())
print(pca_plot())
})
Warning: Error in : C stack usage  1917728 is too close to the limit
163: <Anonymous>
162: stop
161: value[[3L]]
160: tryCatchOne
159: tryCatchList
158: tryCatch
157: do
156: hybrid_chain
128: drawPlot
114: <reactive:plotObj>
98: drawReactive
85: renderFunc
84: output$pca-pca_plot_obj
3: runApp
2: print.shiny.appobj
1: <Anonymous>
=> fix name issue in 2D PCA plot

R/fct_04_pca.R, R/mod_04_pca.R
Looks great. I merged it in. Only minor issue is the title of the legend. "pcaData[[selected_color]]".
Yes, we can get rid of the non-interactive version.
=> fix naming issue and remove non-interactive

DESCRIPTION, R/fct_02_pre_process.R, R/mod_01_load_data.R, R/mod_02_pre_process.R
in edgeR if an sample has all 02 then an error is thrown.
https://github.com/nf-core/smrnaseq/issues/134
This code will check if samples have all 0s and tell the user that they should remove it.
Refactor pre_process to start out with the worst return and add values if they get to that point in the workflow. If a sample has all 0s it will return early so the error is not thrown.
=> fix issue by checking when if sample has all 0s

R/fct_01_load_data.R
Some gene ids is like
ENSG00000267023Ê
This cause errors with toupper
toupper(ENSG00000267023Ê)
This is solved using the iconv function
=> file load error with Latin encoded special characters in gene names

R/app_server.R, R/fct_01_load_data.R, R/mod_01_load_data.R, R/mod_02_pre_process.R
**Description:**
Improved the ability to read strings like "1,120" as numbers. This enhancement has been applied to both CSV and tab formats to maintain consistency across workflows.
Resolved the issue reported in #569 
**Handling of NA Values:**
Proposed Approach: If a cell contains an NA value, we should consider removing the corresponding gene (row). The user will be informed that a cell had an NA value, leading to the removal of the associated row.
To provide transparency, I've integrated a table that displays rows removed due to values that couldn't be interpreted as numbers (resulting in NA). This feature will be especially useful in cases where the input file might contain unexpected content, such as a stray word.
Addressed an edge case where the 'remove data' dataframe might have …
=> Enhanced Number Parsing & Handling of NA Values

R/mod_11_enrichment.R
fix issue #523 . User input for cluster number will stay as selected in the plot tab and other enrichment tabs (within clustering tab).
=> cluster auto change issue

R/fct_04_pca.R, R/mod_04_pca.R
* Resolved errors with large data and PCA plots that involved insufficient values in manual ggplot scales.
* Solution:
* Allow number of shapes available in manual scaling to match or exceed the number of colors in manual scaling.
* Plotly only accepts certain shapes, so some were repeated using rep() and a dynamic number of shapes (nshapes) matching the number of samples.
Note: Also removes "subsetting" of PCA  data if there are more than 100 columns.
* Made shapes and colors consistent between all plots (PCA/PCA, PCA/3D, PCA/MDS, PCA/t_SNE) using plotly-accepted shapes and dynamic variable nshapes
* Made tooltips for PCA plots more informative (MDS and t_SNE are now plotly plots)
=> PCA Large Data and Symbol/Color Consistency Fixes

R/mod_05_deg.R
* Fixed remaining additions mentioned in later comments on this issue
* Download button name changed from "Results & data" to "Enriched Gene List" as suggested, since there is already a button labeled "Results & data" on this tab.
* Added a few lines to filter out "unenriched" genes, only keeping those that are up and down regulated in the downloaded file.
=> Download Enriched Genes Fix

R/mod_01_load_data.R
* Added default values "None" and "No data type selected" for Species and Data Type selection, respectively
* Demo options and File Inputs are now conditional on these default values
* These options will no longer appear until default values are not selected
* This forces users to select a species and data type before uploading data or loading a demo
* Added a notification to the bottom left to notify users of this process
=> User Manual Selection Feature

R/fct_09_network.R, R/mod_09_network.R
* Nodes in networks plots will now always have a name attached
* Previously, gene names from uploaded data were swapped with ensembl IDs and Symbols, but these don't always match what is submitted, depending on the user's observed ID system
* Now, if uploaded IDs do not have a match, they are kept instead of switched to NA, leaving the submitted ID in the adjacency matrix and network plots
**Extra:** Added extra req() statements for WGCNA data, adjacency matrix, and network plot to avoid edge cases, which previously crashed the app if Network inputs were NA
=> Network Gene Name Fix

DESCRIPTION, R/fct_09_network.R, R/mod_09_network.R, dev/02_dev.R
* Changed network plotting method from plot() function to ggraph() object
* ggraph option is easier to work with and download than previous method
* Leaves less white space on the Network tab than the previous method
* Added download options for both Network and Module plots
* Module dendrogram class does not work with the ottoPlots package, so it currently only has .png format with fixed width
* Made several file names dynamic
* Changed size of points and text on the new network plot to be readable
=> Network and Module Plot Downloads

R/mod_01_load_data.R, R/mod_02_pre_process.R, R/mod_03_clustering.R, R/mod_05_deg.R, R/mod_08_bicluster.R, R/mod_09_network.R, R/mod_11_enrichment.R
* Pre-process module now passes the number of filtered genes to any tab that uses the Enrichment module
* If there are below 1000 filtered genes, the filtered genes will not be used as the default background for enrichment analysis
* All genes used instead
* Message displayed to user by the Pre-processing tab when this occurs
=> Enrichment Default Background

R/fct_03_clustering.R, R/mod_03_clustering.R
* Added "Top 5", "Top 10", and "Top 15" options to the "Label Genes:" input on the clustering tab
* This takes the top genes from the heatmap data, which is already sorted by standard deviation, and passes them as a group to the labeling portion of the heatmap function
* These options will be automatically loaded as choices for the input box so the users can select prior to clustering
=> Clustering Top Gene Labels

R/mod_01_load_data.R
* Instead of expanding all options, which would congest the page, we can make the global options stand out in other ways
* Changed "Global Settings" checkbox text to red, to increase noticeability
=> Global Settings Color Change

R/app_server.R, R/fct_11_enrichment.R, R/mod_01_load_data.R, R/mod_03_clustering.R, R/mod_05_deg.R, R/mod_06_pathway.R, R/mod_08_bicluster.R, R/mod_09_network.R, R/mod_11_enrichment.R, man/enrichment_network.Rd, man/network_data.Rd
* Changed colors of Tree and Network plots in the Enrichment and Pathway modules
* Colors now match first and last colors of the global setting for the heatmap color scheme
* Needed to pass global setting to all tabs that use the Enrichment module
* Removed leaf color selection in Pathway/Tree tab
* Changed labels for color scheme selection in global settings to make them more descriptive for users
=> Tree & Network Plot Colors

R/mod_03_clustering.R, R/mod_12_heatmap.R
* Fixed Clustering tab heatmap so users can select outside of heatmap bounds (cells) without getting stuck on the spinner (a fatal error)
* Sub-heatmap no longer attempts to render when selections do not contain cells
* Expanded fix for blank sub-heatmap selection to the heatmap module (used for Bicluster, Pathway, etc.)
* Users will no longer receive errors or be stuck with the loading icon over their screen (fatal) if they select a blank area on the heatmaps in the app
=> Heatmap Out of Bounds Selection
